# Generated by Django 2.1.4 on 2019-01-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190106_0851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
