# Generated by Django 2.1.4 on 2019-01-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
