# Generated by Django 2.1.4 on 2019-01-06 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190106_1220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
