# Generated by Django 2.1.5 on 2019-01-14 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdApp', '0003_bottle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bottle',
        ),
    ]
