# Generated by Django 2.1.4 on 2019-01-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogIn', '0003_auto_20190105_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id',
            new_name='user',
        ),
    ]
