# Generated by Django 2.1.4 on 2019-01-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogIn', '0005_auto_20190105_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
