# Generated by Django 2.1.4 on 2019-01-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogIn', '0009_auto_20190105_1834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
