# Generated by Django 2.1.4 on 2019-01-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogIn', '0010_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
