# Generated by Django 2.1.4 on 2019-01-07 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogIn', '0017_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
